apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: test-package
  namespace: testpackage
spec:
  interval: 1m
  chart:
    spec:
      chart: example
      version: '0.1.0'
      sourceRef:
        kind: HelmRepository
        name: test-package
        namespace: testpackage
      reconcileStrategy: Revision
      interval: 1m
  targetNamespace: testpackage
  valuesFrom:
    - kind: ConfigMap
      name: test-package-values
      valuesKey: values.yaml
