apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: example
  namespace: mypackage
spec:
  interval: 1m
  chart:
    spec:
      chart: example
      version: '0.1.0'
      sourceRef:
        kind: HelmRepository
        name: helm-charts
        namespace: mypackage
      reconcileStrategy: Revision
      interval: 1m
  targetNamespace: mypackage
  valuesFrom:
    - kind: ConfigMap
      name: example-values
      valuesKey: values.yaml
