apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: online-boutique
  namespace: online-boutique
spec:
  interval: 1m
  chart:
    spec:
      chart: onlineboutique
      version: '0.8.x'
      sourceRef:
        kind: HelmRepository
        name: online-boutique
        namespace: online-boutique
      reconcileStrategy: Revision
      interval: 1m
  targetNamespace: online-boutique
  valuesFrom:
  - kind: ConfigMap
    name: online-boutique-values
    valuesKey: values.yaml