apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: test-helm-package
  namespace: testhelm
spec:
  interval: 1m
  chart:
    spec:
      chart: example
      version: '0.1.0'
      sourceRef:
        kind: HelmRepository
        name: test-helm-package
        namespace: testhelm
      reconcileStrategy: Revision
      interval: 1m
  targetNamespace: testhelm
  valuesFrom:
    - kind: ConfigMap
      name: test-helm-package-values
      valuesKey: values.yaml
