apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ueransim
  namespace: demo
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/ueransim 
      version: '2.0.x'
      sourceRef:
        kind: GitRepository
        name: free5gc-gitrepo
        namespace: flux-system
      reconcileStrategy: Revision
      interval: 1m
  targetNamespace: demo
  valuesFrom:
  - kind: ConfigMap
    name: ue-values
    valuesKey: values.yaml
