apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: free5gc 
  namespace: demo
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/free5gc 
      version: '1.1.x'
      sourceRef:
        kind: GitRepository
        name: free5gc-gitrepo
        namespace: flux-system
      reconcileStrategy: Revision
      interval: 1m
  targetNamespace: demo
  valuesFrom:
  - kind: ConfigMap
    name: 5gc-values
    valuesKey: values.yaml

